### PR TITLE
Add option to check markdowns inside folder

### LINKED ISSUE #14: Support for folder with multiple files
I'd love to see support for folders as I have many files in a single folder that I'd like to count.

### PR DESCRIPTION
**Pull request by alexandrebarbaruiva**
Add option to check all markdown files inside a specific folder. We've (@emmenezes and I) included tests. Currently it's not recursive due to many changes in single PR.

Also it was added a file verification (previously it was counting any type of file with text)
Also also, the print was changed to display the file name 

closes #14

### CODE REVIEW

**Comment by gandreadis** [comment]
Awesome work, thanks a lot for this!!

I have a couple of small requests before we can include this:

1. Could you add a short text about this to the README? Basically telling users that you can also pass a folder.
2. The current change also means that people using only one file as input will have a breaking change - the output will no longer just consist of the number, but also of the file name. I'd prefer if for now, the tool just outputs one count (one number, for the folder it would be then a total summed count), without any headings, to make use in CIs and the like easier. We can add a special option for more detailed output, but the single-number output should be the default. Do you agree?

**Comment by alexandrebarbaruiva** [comment]
About your feedback:
1. I'll add a description to the README
2. Makes perfect sense, I'll change the code to maintain compatibility!

However, I might take a bit of time to make these changes, I'm currently in
my busy week. I'll possibly work on it by next weekend.

Em sex., 28 de ago. de 2020 às 14:13, Georgios Andreadis <
notifications@github.com> escreveu:

**Comment by gandreadis** [comment]
@alexandrebarbaruiva No worries, sounds great! :)

**Comment by gandreadis** [comment]
Hi @alexandrebarbaruiva, it's been a while, but did you get a chance to apply my two points of feedback? Thanks in advance!

**Comment by gandreadis** [comment]
Closing due to inactivity and the fix provided in a different PR.

**Pull request closed without merging**
